FROM node:18-alpine

WORKDIR /app

# Установка зависимостей
COPY package*.json ./
RUN npm ci

# Копирование исходного кода
COPY . .

# Генерация Prisma клиента
RUN npx prisma generate

EXPOSE 4000

ENV PORT 4000
ENV NODE_ENV production

CMD ["npx", "tsx", "websocket-server.ts"]
