version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: epassport
      POSTGRES_PASSWORD: epassport123
      POSTGRES_DB: epassport
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://epassport:epassport123@db:5433/epassport
      - JWT_SECRET=your-secret-key-here
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
